# Generated by Django 5.0.6 on 2024-05-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_menu_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='item_price',
        ),
    ]
