# Generated by Django 5.0.6 on 2024-05-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_menu_item_description_menu_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='item_price',
            new_name='price',
        ),
    ]
